package com.khatago.finance.data.db.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.serialization.Transient

/**
 * KhataGo's persisted schema (Room database version 1).
 *
 * Three rules govern every entity here, and they are the reason the money model is trustworthy:
 *
 * 1. **Amounts are `Long` minor units.** No `Float`, no `Double`, no numeric strings. `10050`
 *    means ৳100.50. A `REAL` column would eventually print ৳0.30000000000000004 in a report.
 * 2. **No derived amount is stored.** There is no `remaining` / `totalPaid` column on any
 *    obligation: those are computed from the payment ledger on every read (see `FinancialMath`).
 *    A stored total drifts the moment a payment is edited or deleted, and a drifted number in a
 *    money app is a bug the user discovers months later.
 * 3. **Dates that mean something to a human are epoch-day integers** (a local calendar day), not
 *    instants, so a due date never shifts across a timezone or DST change. Machine timestamps use
 *    epoch milliseconds.
 *
 * Column names follow the Kotlin property names (Room's default) — deliberately, not lazily:
 * a single naming rule means hand-written aggregate SQL and the projection classes below it can
 * never disagree about whether a column is `amountMinor` or `amount_minor`.
 *
 * Property names are also the backup JSON field names, so the export format is readable and
 * stable. `app/schemas/<table>/1.json` is generated by the build and is the source of truth for
 * migrations.
 */

@Entity(tableName = "profile")
data class ProfileEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val displayName: String? = null,
    val currencyCode: String = "BDT",
    val countryCode: String? = null,
    val avatarUri: String? = null,
    /** 0 means "goal not set" — distinct from a genuine ৳0 target. */
    val monthlyIncomeGoalMinor: Long = 0,
    val monthlyExpenseGoalMinor: Long = 0,
    val onboardingComplete: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * A shop the user buys from on credit. No denormalised balance columns: a shop's outstanding
 * amount is always the sum of its credits minus the payments recorded against those credits.
 */
@Entity(
    tableName = "shops",
    indices = [Index(value = ["name"], unique = true)],
)
data class ShopEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val name: String,
    val ownerName: String? = null,
    val phone: String? = null,
    val address: String? = null,
    val category: String? = null,
    val notes: String? = null,
    val photoUri: String? = null,
    val archived: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * A single credit purchase at a shop — one line of the market khata.
 *
 * `quantity x unitPriceMinor` is kept next to `totalAmountMinor` rather than replacing it: the
 * agreed notebook total sometimes includes a discount or rounding the user wants to keep exactly.
 * The repository validates that the two agree unless `overrideTotal` says the total was typed on
 * purpose, so a mistyped unit price cannot silently rewrite what is owed.
 */
@Entity(
    tableName = "shop_credits",
    indices = [Index("shopId"), Index("dueDateEpochDay"), Index("purchaseDateEpochDay"), Index("cancelled")],
    foreignKeys = [
        ForeignKey(
            entity = ShopEntity::class,
            parentColumns = ["id"],
            childColumns = ["shopId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
)
data class ShopCreditEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val shopId: Long,
    val productName: String,
    val quantity: Long = 1,
    val unitPriceMinor: Long = 0,
    val totalAmountMinor: Long,
    val overrideTotal: Boolean = false,
    val purchaseDateEpochDay: Long,
    val dueDateEpochDay: Long? = null,
    val notes: String? = null,
    val cancelled: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * A person the user has money with. One row can hold both borrowings (the user owes them) and
 * lendings (they owe the user): a single identity table is what stops "Karim" becoming two
 * unrelated records with split balances.
 */
@Entity(
    tableName = "people",
    indices = [Index(value = ["name", "relationship"], unique = true)],
)
data class PersonEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val name: String,
    val relationship: String = RELATIONSHIP_OTHER,
    val phone: String? = null,
    val notes: String? = null,
    val photoUri: String? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
) {
    companion object {
        val RELATIONSHIPS = listOf("Friend", "Relative", "Family", "Colleague", "Neighbor", "Other")
        const val RELATIONSHIP_OTHER = "Other"
    }
}

/** Money the user **owes** a person. */
@Entity(
    tableName = "borrowings",
    indices = [Index("personId"), Index("dueDateEpochDay"), Index("cancelled")],
    foreignKeys = [
        ForeignKey(
            entity = PersonEntity::class,
            parentColumns = ["id"],
            childColumns = ["personId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
)
data class BorrowingEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val personId: Long,
    val amountMinor: Long,
    val borrowDateEpochDay: Long,
    val dueDateEpochDay: Long? = null,
    val notes: String? = null,
    val cancelled: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * Money a person **owes the user**. Its own table, on purpose: keeping it structurally separate
 * from `borrowings` is what makes "sum the two together by mistake" impossible in SQL.
 */
@Entity(
    tableName = "lendings",
    indices = [Index("personId"), Index("dueDateEpochDay"), Index("cancelled")],
    foreignKeys = [
        ForeignKey(
            entity = PersonEntity::class,
            parentColumns = ["id"],
            childColumns = ["personId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
)
data class LendingEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val personId: Long,
    val amountMinor: Long,
    val lendDateEpochDay: Long,
    val dueDateEpochDay: Long? = null,
    val notes: String? = null,
    val cancelled: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * A bank/NGO loan.
 *
 * Terms are entered as agreed, not computed. KhataGo deliberately does not model interest: flat
 * rate, reducing balance and NGO micro-loan schemes all disagree, and guessing one would put wrong
 * numbers on screen. `interestRatePercent` is stored for reference and shown on the record; it is
 * never used to derive an amount.
 */
@Entity(
    tableName = "loans",
    indices = [Index("institution"), Index("endDateEpochDay"), Index("cancelled")],
)
data class LoanEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val institution: String,
    val loanName: String,
    val principalMinor: Long,
    val disbursementDateEpochDay: Long,
    val interestRatePercent: Double = 0.0,
    val totalPayableMinor: Long,
    val downPaymentMinor: Long = 0,
    val installmentAmountMinor: Long,
    val installmentCount: Int,
    /** [com.khatago.finance.core.time.Frequency] name. */
    val installmentFrequency: String = "Monthly",
    val customIntervalDays: Int = 30,
    val startDateEpochDay: Long,
    val firstDueDateEpochDay: Long,
    val endDateEpochDay: Long? = null,
    val contactName: String? = null,
    val contactPhone: String? = null,
    val notes: String? = null,
    val cancelled: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/** An EMI / installment purchase: phone, laptop, fridge, furniture, motorcycle, ... */
@Entity(
    tableName = "emi_purchases",
    indices = [Index("merchant"), Index("endDateEpochDay"), Index("cancelled")],
)
data class EmiPurchaseEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val productName: String,
    val merchant: String,
    val purchaseDateEpochDay: Long,
    val cashPriceMinor: Long = 0,
    val totalPayableMinor: Long,
    val downPaymentMinor: Long = 0,
    val emiAmountMinor: Long,
    val installmentCount: Int,
    val installmentFrequency: String = "Monthly",
    val customIntervalDays: Int = 30,
    val firstDueDateEpochDay: Long,
    val endDateEpochDay: Long? = null,
    val notes: String? = null,
    val cancelled: Boolean = false,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * One scheduled repayment of a loan or an EMI purchase.
 *
 * `ownerType` + `ownerId` is a discriminated link (same mechanism as the payment ledger) because a
 * loan installment and an EMI installment behave identically; duplicating the table would double
 * every query and every bug. `paidMinor` records only what was paid at this line — the
 * authoritative per-line position is computed by `InstallmentAllocator`, which is what guarantees
 * the schedule can never contradict the obligation's headline balance.
 */
@Entity(
    tableName = "installments",
    indices = [
        Index(value = ["ownerType", "ownerId"]),
        Index("dueDateEpochDay"),
    ],
)
data class InstallmentEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val ownerType: String,
    val ownerId: Long,
    val number: Int,
    val dueDateEpochDay: Long,
    val scheduledAmountMinor: Long,
    val paidMinor: Long = 0,
    /** True when the user edited the line, so a schedule regeneration must not clobber it. */
    val manual: Boolean = false,
    val createdAt: Long = 0,
)

/**
 * The payment ledger: the only place KhataGo records money actually moving against an obligation.
 *
 * Payments are independent rows linked by (payableType, payableId), which is what makes editing or
 * deleting a payment safe — balances are recomputed and history is never destructively merged into
 * the obligation.
 */
@Entity(
    tableName = "payments",
    indices = [
        Index(value = ["payableType", "payableId"]),
        Index("paidDateEpochDay"),
        Index("installmentId"),
    ],
    // payableId is intentionally NOT a foreign key. It is polymorphic (shop_credits, loans,
    // emi_purchases, borrowings or lendings, chosen by payableType) and SQLite cannot express
    // "FK into one of five tables" — a one-table FK would silently accept an unrelated row whose
    // id happens to collide. Referential integrity is enforced in the repository layer instead,
    // in the same transaction as the delete, and is covered by database tests.
    foreignKeys = [
        ForeignKey(
            entity = InstallmentEntity::class,
            parentColumns = ["id"],
            childColumns = ["installmentId"],
            onDelete = ForeignKey.SET_NULL,
        ),
    ],
)
data class PaymentEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val payableType: String,
    val payableId: Long,
    val installmentId: Long? = null,
    val amountMinor: Long,
    val paidDateEpochDay: Long,
    val methodName: String = "Cash",
    val reference: String? = null,
    val note: String? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

@Entity(
    tableName = "payment_methods",
    indices = [Index(value = ["name"], unique = true)],
)
data class PaymentMethodEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val name: String,
    val orderIndex: Int = 0,
    val builtIn: Boolean = false,
    val enabled: Boolean = true,
) {
    companion object {
        /** Cash first: it is the overwhelmingly common path in a khata workflow. */
        val DEFAULTS = listOf("Cash", "Bank transfer", "Mobile banking", "Card", "Other")
    }
}

@Entity(
    tableName = "categories",
    indices = [Index(value = ["kind", "name"], unique = true)],
)
data class CategoryEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    /** "income" or "expense"; the same display name may exist once per kind. */
    val kind: String,
    val name: String,
    val orderIndex: Int = 0,
    val builtIn: Boolean = false,
    val enabled: Boolean = true,
) {
    companion object {
        const val KIND_INCOME = "income"
        const val KIND_EXPENSE = "expense"

        val INCOME_DEFAULTS = listOf(
            "Salary", "Business", "Freelance", "Bonus", "Commission", "Gift", "Investment", "Other",
        )

        val EXPENSE_DEFAULTS = listOf(
            "Food", "Transport", "Shopping", "Bills", "Rent", "Utilities", "Education", "Health",
            "Family", "Entertainment", "Business", "Loan Payment", "EMI Payment", "Other",
        )
    }
}

/** Money coming in. Not part of any obligation: a cash-flow record. */
@Entity(
    tableName = "incomes",
    indices = [Index("transactionDateEpochDay"), Index("categoryName"), Index("amountMinor")],
)
data class IncomeEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val amountMinor: Long,
    val source: String? = null,
    val categoryName: String = "Other",
    val transactionDateEpochDay: Long,
    val methodName: String = "Cash",
    val note: String? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

@Entity(
    tableName = "expenses",
    indices = [Index("transactionDateEpochDay"), Index("categoryName"), Index("amountMinor")],
)
data class ExpenseEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val amountMinor: Long,
    val categoryName: String = "Other",
    val merchant: String? = null,
    val transactionDateEpochDay: Long,
    val methodName: String = "Cash",
    val note: String? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * An image (receipt, product photo, agreement page) attached to a record.
 *
 * Files live in the app's private `attachments/` directory, downscaled and recompressed at import
 * so a 12 MP camera JPEG cannot blow up memory or storage. Only the file name is persisted, so a
 * reinstall can re-resolve the path; a missing file degrades to "attachment unavailable" rather
 * than a broken screen.
 */
@Entity(
    tableName = "attachments",
    indices = [Index(value = ["targetType", "targetId"])],
)
data class AttachmentEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val targetType: String,
    val targetId: Long,
    val fileName: String,
    val originalName: String? = null,
    val mimeType: String = "image/jpeg",
    val sizeBytes: Long = 0,
    val createdAt: Long = 0,
) {
    companion object {
        const val TARGET_SHOP = "shop"
        const val TARGET_SHOP_CREDIT = "shop_credit"
        const val TARGET_PERSON = "person"
        const val TARGET_LOAN = "loan"
        const val TARGET_EMI = "emi"
        const val TARGET_BORROWING = "borrowing"
        const val TARGET_LENDING = "lending"
        const val TARGET_INCOME = "income"
        const val TARGET_EXPENSE = "expense"
        const val TARGET_PAYMENT = "payment"
    }
}

/**
 * A user-authored reminder. Automatic due reminders are *derived* from due dates and need no rows;
 * this table is for the notes-to-self a person adds deliberately ("collect the deed paper on the
 * 9th"). Included in backups for completeness.
 */
@Entity(
    tableName = "reminders",
    indices = [Index("dueDateEpochDay"), Index(value = ["entityType", "entityId"])],
)
data class ReminderEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val entityType: String? = null,
    val entityId: Long? = null,
    val title: String,
    val note: String? = null,
    val dueDateEpochDay: Long,
    /** Minute of day, local. */
    val dueTimeMinute: Int = 18 * 60,
    val enabled: Boolean = true,
    val lastFiredEpochDay: Long? = null,
    val createdAt: Long = 0,
)

/**
 * Notification dedupe ledger: one row per (obligation, calendar day) a reminder was posted for.
 * "No spam" is therefore a structural property enforced by a UNIQUE index, not a promise in the
 * notification code.
 */
@Entity(
    tableName = "reminder_log",
    indices = [
        Index(value = ["dedupeKey"], unique = true),
        Index("dueDateEpochDay"),
    ],
)
data class ReminderLogEntity(
    @PrimaryKey(autoGenerate = true) @Transient val id: Long = 0,
    val dedupeKey: String,
    val entityType: String,
    val entityId: Long,
    val dueDateEpochDay: Long,
    val postedAt: Long,
)

/**
 * Non-sensitive key/value settings. Sensitive values (the app-lock PIN) never land here: they are
 * stored as a salted PBKDF2 digest by `SecurityRepository`.
 */
@Entity(tableName = "app_settings", primaryKeys = ["key"])
data class AppSettingEntity(
    val key: String,
    val value: String,
    val updatedAt: Long = 0,
) {
    companion object {
        const val NOTIFICATIONS_ENABLED = "notifications_enabled"
        const val REMINDER_HOUR = "reminder_hour"
        const val REMIND_DUE_TOMORROW = "remind_due_tomorrow"
        const val REMIND_DUE_TODAY = "remind_due_today"
        const val REMIND_OVERDUE = "remind_overdue"
        const val BIOMETRIC_ENABLED = "biometric_enabled"
        const val DASHBOARD_WIDGETS_HIDDEN = "dashboard_widgets_hidden"
        const val SAMPLE_DATA_LOADED = "sample_data_loaded"
    }
}
