package com.khatago.finance.ui.forms

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.khatago.finance.AppContainer
import com.khatago.finance.core.money.CurrencySpec
import com.khatago.finance.core.money.MoneyFormat
import com.khatago.finance.core.money.MoneyParseResult
import com.khatago.finance.core.time.AppDates
import com.khatago.finance.core.time.Frequency
import com.khatago.finance.data.db.entity.EmiPurchaseEntity
import com.khatago.finance.data.db.entity.LoanEntity
import com.khatago.finance.data.repo.SaveResult
import com.khatago.finance.ui.components.AmountField
import com.khatago.finance.ui.components.DateField
import com.khatago.finance.ui.components.DropdownField
import com.khatago.finance.ui.components.FieldContext
import com.khatago.finance.ui.components.FormSection
import com.khatago.finance.ui.components.NoteField
import com.khatago.finance.ui.components.PrimaryButton
import com.khatago.finance.ui.components.TextFieldLine
import com.khatago.finance.ui.theme.KhataGoColors
import com.khatago.finance.ui.theme.KhataGoRadii
import com.khatago.finance.ui.theme.KhataGoSpacing
import kotlinx.coroutines.launch

/**
 * The loan and EMI forms — the two places where KhataGo could easily produce a wrong schedule, so
 * both do the same three things:
 *
 *  1. **Show the schedule before it is saved.** The preview is generated by the same
 *     `InstallmentSchedule` the repository uses to persist rows, so what you see is literally what is
 *     written — not a reimplementation in the UI that could round differently.
 *  2. **Treat the down payment as already-paid**, which is how a real agreement reads. It is entered
 *     once here and never as a "payment", because a payment that also matches a schedule line would
 *     be counted twice.
 *  3. **Refuse nonsense with words, not with clamps.** A count of 600 installments or a total payable
 *     below the principal is rejected by `validateLoan`/`validateEmi` with the reason, because silently
 *     clamping a number is how a ledger ends up containing something the user did not type.
 */
@Composable
fun LoanFormRoute(container: AppContainer, editId: Long? = null, onDone: () -> Unit) {
    ObligationForm(
        container = container,
        kind = "loan",
        title = if (editId == null) "Add a loan" else "Edit loan",
        editId = editId,
        onDone = onDone,
    )
}

@Composable
fun EmiFormRoute(container: AppContainer, editId: Long? = null, onDone: () -> Unit) {
    ObligationForm(
        container = container,
        kind = "emi",
        title = if (editId == null) "Add an EMI plan" else "Edit EMI plan",
        editId = editId,
        onDone = onDone,
    )
}

@Composable
private fun ObligationForm(
    container: AppContainer,
    kind: String,
    title: String,
    onDone: () -> Unit,
    editId: Long? = null,
) {
    val scope = rememberCoroutineScope()
    val today = remember { AppDates.today() }
    val isLoan = kind == "loan"

    var currency by remember { mutableStateOf(CurrencySpec.DEFAULT) }
    var institution by remember { mutableStateOf("") }
    var loanName by remember { mutableStateOf("") }
    var product by remember { mutableStateOf("") }
    var merchant by remember { mutableStateOf("") }
    var principalText by remember { mutableStateOf("") }
    var cashPriceText by remember { mutableStateOf("") }
    var totalPayableText by remember { mutableStateOf("") }
    var downPaymentText by remember { mutableStateOf("") }
    var installmentAmountText by remember { mutableStateOf("") }
    var countText by remember { mutableStateOf("12") }
    var frequency by remember { mutableStateOf(Frequency.Monthly) }
    var customDays by remember { mutableStateOf("30") }
    var rateText by remember { mutableStateOf("") }
    var purchaseDate by remember { mutableStateOf(today) }
    var disbursementDate by remember { mutableStateOf(today) }
    var firstDue by remember { mutableStateOf<Long?>(today + 30) }
    var contactName by remember { mutableStateOf("") }
    var contactPhone by remember { mutableStateOf("") }
    var notes by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }
    var saving by remember { mutableStateOf(false) }

    LaunchedEffect(editId) {
        currency = CurrencySpec.fromCode(container.catalogRepository.findProfile()?.currencyCode)
        // An edit prefills every field, including the ones this form would otherwise default (dates,
        // frequency, down payment). A partial prefill is worse than none: the untouched defaults get
        // written back over the stored values, quietly rewriting history.
        if (editId != null && isLoan) {
            container.obligationRepository.findLoan(editId)?.let { loan ->
                institution = loan.institution
                loanName = loan.loanName
                principalText = MoneyFormat.toCsvNumber(loan.principalMinor, currency)
                totalPayableText = MoneyFormat.toCsvNumber(loan.totalPayableMinor, currency)
                downPaymentText = MoneyFormat.toCsvNumber(loan.downPaymentMinor, currency)
                installmentAmountText = MoneyFormat.toCsvNumber(loan.installmentAmountMinor, currency)
                countText = loan.installmentCount.toString()
                frequency = Frequency.entries.firstOrNull { it.name == loan.installmentFrequency }
                    ?: Frequency.Monthly
                customDays = loan.customIntervalDays.toString()
                rateText = if (loan.interestRatePercent > 0.0) {
                    loan.interestRatePercent.toString()
                } else {
                    ""
                }
                disbursementDate = loan.disbursementDateEpochDay
                firstDue = loan.firstDueDateEpochDay
                contactName = loan.contactName ?: ""
                contactPhone = loan.contactPhone ?: ""
                notes = loan.notes ?: ""
            }
        } else if (editId != null) {
            container.obligationRepository.findEmi(editId)?.let { emi ->
                product = emi.productName
                merchant = emi.merchant
                purchaseDate = emi.purchaseDateEpochDay
                cashPriceText = MoneyFormat.toCsvNumber(emi.cashPriceMinor, currency)
                totalPayableText = MoneyFormat.toCsvNumber(emi.totalPayableMinor, currency)
                downPaymentText = MoneyFormat.toCsvNumber(emi.downPaymentMinor, currency)
                installmentAmountText = MoneyFormat.toCsvNumber(emi.emiAmountMinor, currency)
                countText = emi.installmentCount.toString()
                frequency = Frequency.entries.firstOrNull { it.name == emi.installmentFrequency }
                    ?: Frequency.Monthly
                customDays = emi.customIntervalDays.toString()
                firstDue = emi.firstDueDateEpochDay
                notes = emi.notes ?: ""
            }
        }
    }

    val context = FieldContext(currency = currency, todayEpochDay = today)
    fun amount(field: String): Long =
        (MoneyParseResult.parse(field, currency, allowZero = true) as? MoneyParseResult.Success)?.amount?.minor ?: 0L

    val principal = amount(if (isLoan) principalText else cashPriceText)
    val totalPayable = amount(totalPayableText)
    val downPayment = amount(downPaymentText)
    val installmentAmount = amount(installmentAmountText)
    val count = countText.toIntOrNull()?.coerceIn(0, 600) ?: 0
    val customInterval = customDays.toIntOrNull()?.coerceIn(1, 365) ?: 30

    // Derived, in the direction the user left blank: leaving the installment amount out is the common
    // case ("I know the total and the number of months"), and inventing a rounding here would be the
    // repository's job — so the preview uses the same helper it does.
    val effectiveTotal = if (totalPayable > 0L) totalPayable else principal
    val preview = remember(
        firstDue, count, frequency, customInterval, installmentAmount, effectiveTotal,
    ) {
        if (count > 0 && (installmentAmount > 0L || effectiveTotal > 0L)) {
            container.obligationRepository.previewSchedule(
                firstDueDateEpochDay = firstDue,
                count = count,
                frequency = frequency,
                customIntervalDays = customInterval,
                installmentMinor = installmentAmount,
                // Deliberately *not* `effectiveTotal - downPayment`: `saveEmi` schedules from
                // `totalPayableMinor - downPaymentMinor` itself, so subtracting here would preview a
                // schedule shorter than the one that gets written (and, on an edit, would show a
                // different plan from the one stored).
                totalPayableMinor = if (installmentAmount > 0L) null else effectiveTotal,
            )
        } else {
            emptyList()
        }
    }

    FormScaffold(title = title, onBack = onDone) {
        FormSection(title = if (isLoan) "The loan" : "The purchase") {
            if (isLoan) {
                TextFieldLine(
                    value = institution,
                    onValueChange = { institution = it },
                    label = "Bank / NGO / lender",
                    required = true,
                    placeholder = "Sonali Bank, BRAC, a friend…",
                )
                TextFieldLine(
                    value = loanName,
                    onValueChange = { loanName = it },
                    label = "Loan name",
                    required = true,
                    placeholder = "Agriculture loan 2026",
                )
            } else {
                TextFieldLine(
                    value = product,
                    onValueChange = { product = it },
                    label = "What you are buying",
                    required = true,
                    placeholder = "Smartphone, refrigerator, motorbike…",
                )
                TextFieldLine(
                    value = merchant,
                    onValueChange = { merchant = it },
                    label = "Shop or provider",
                    required = true,
                    placeholder = "Rahman Electronics",
                )
                AmountField(
                    value = cashPriceText,
                    onValueChange = { cashPriceText = it },
                    context = context,
                    label = "Cash price",
                    required = false,
                    helper = "Optional. Compared against the total payable so a swap of the two figures is caught.",
                )
            }
            if (isLoan) {
                AmountField(
                    value = principalText,
                    onValueChange = { principalText = it },
                    context = context,
                    label = "Amount you received",
                )
            }
            AmountField(
                value = totalPayableText,
                onValueChange = { totalPayableText = it },
                context = context,
                label = if (isLoan) "Total payable (principal + interest)" else "Total payable (all EMIs + down payment)",
                helper = when {
                    isLoan && principal > 0L && effectiveTotal > principal ->
                        "Interest included: ${MoneyFormat.format(effectiveTotal - principal, currency)}"
                    isLoan -> "The full amount you will have paid by the end."
                    else -> "The whole cost on this plan, including the down payment you already paid. " +
                        "The schedule below covers what is left."
                },
            )
            if (isLoan) {
                TextFieldLine(
                    value = rateText,
                    onValueChange = { rateText = it.filter { ch -> ch.isDigit() || ch == '.' } },
                    label = "Interest rate (informational)",
                    placeholder = "12",
                    keyboardType = KeyboardType.Decimal,
                    helper = "Stored only — KhataGo never recomputes your instalments from it, so a " +
                        "rate written in your agreement can be kept next to the real numbers.",
                )
            }
        }

        FormSection(title = "Schedule") {
            AmountField(
                value = downPaymentText,
                onValueChange = { downPaymentText = it },
                context = context,
                label = "Down payment",
                required = false,
                helper = "Counted as already paid from day one; it is not a separate payment record.",
            )
            Row(horizontalArrangement = Arrangement.spacedBy(KhataGoSpacing.md)) {
                Box(modifier = Modifier.weight(1f)) {
                    TextFieldLine(
                        value = countText,
                        onValueChange = { countText = it.filter { ch -> ch.isDigit() } },
                        label = "Number of installments",
                        keyboardType = KeyboardType.Number,
                    )
                }
                Box(modifier = Modifier.weight(1f)) {
                    AmountField(
                        value = installmentAmountText,
                        onValueChange = { installmentAmountText = it },
                        context = context,
                        label = "Each installment",
                        required = false,
                        helper = if (installmentAmount == 0L && effectiveTotal > 0L && count > 0) {
                            "Leave blank to split evenly"
                        } else {
                            null
                        },
                    )
                }
            }
            DropdownField(
                options = Frequency.entries.toList(),
                selected = frequency,
                onSelect = { frequency = it },
                labelOf = { it.label },
                label = "Frequency",
            )
            if (frequency == Frequency.Custom) {
                TextFieldLine(
                    value = customDays,
                    onValueChange = { customDays = it.filter { ch -> ch.isDigit() } },
                    label = "Interval in days",
                    keyboardType = KeyboardType.Number,
                    helper = "End-of-month clamping still applies: a 31 January due date on a " +
                        "30-day interval becomes 28/29 February, not a missing month.",
                )
            }
            if (isLoan) {
                DateField(
                    epochDay = disbursementDate,
                    onEpochDayChange = { disbursementDate = it ?: today },
                    label = "Disbursed on",
                    context = context,
                )
            }
            DateField(
                epochDay = firstDue,
                onEpochDayChange = { firstDue = it },
                label = "First installment due",
                context = context,
                helper = "The rest of the schedule is built from this date.",
            )
        }

        if (preview.isNotEmpty()) {
            FormSection(title = "Preview of your schedule") {
                Text(
                    text = "${preview.size} installment(s) · first ${AppDates.formatMedium(preview.first().dueDateEpochDay)}" +
                        " · last ${AppDates.formatMedium(preview.last().dueDateEpochDay)}",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                preview.take(6).forEach { entry ->
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(vertical = 3.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text(
                            text = "${entry.number}",
                            style = MaterialTheme.typography.labelMedium,
                            modifier = Modifier.width(22.dp),
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                        Text(
                            text = AppDates.formatMediumWithWeekday(entry.dueDateEpochDay),
                            style = MaterialTheme.typography.bodyMedium,
                            modifier = Modifier.weight(1f),
                        )
                        Text(
                            // The preview prints the repository's own per-line amount (which includes the
                            // last-line rounding fix), not a division the form invents.
                            text = MoneyFormat.format(entry.amountMinor, currency),
                            style = MaterialTheme.typography.titleSmall,
                        )
                    }
                }
                if (preview.size > 6) {
                    Text(
                        text = "+ ${preview.size - 6} more",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                Text(
                    text = "Saved as individual lines so each one can be paid early, late or partly — " +
                        "and an edit you make to a single line is marked manual and survives a rebuild.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }

        FormSection(title = "Contacts and notes") {
            if (isLoan) {
                TextFieldLine(value = contactName, onValueChange = { contactName = it }, label = "Officer / contact")
                TextFieldLine(
                    value = contactPhone,
                    onValueChange = { contactPhone = it },
                    label = "Contact phone",
                    keyboardType = KeyboardType.Phone,
                )
            }
            NoteField(value = notes, onValueChange = { notes = it })
        }

        FormError(error)

        PrimaryButton(
            text = "Save",
            loading = saving,
            onClick = {
                error = null
                saving = true
                scope.launch {
                    val result = if (isLoan) {
                        container.obligationRepository.saveLoan(
                            LoanEntity(
                                id = editId ?: 0L,
                                institution = institution.trim(),
                                loanName = (loanName.trim().ifEmpty { "Loan" }),
                                principalMinor = principal,
                                disbursementDateEpochDay = disbursementDate,
                                interestRatePercent = rateText.toDoubleOrNull() ?: 0.0,
                                totalPayableMinor = effectiveTotal,
                                downPaymentMinor = downPayment,
                                installmentAmountMinor = installmentAmount,
                                installmentCount = count,
                                installmentFrequency = frequency.name,
                                customIntervalDays = customInterval,
                                startDateEpochDay = disbursementDate,
                                firstDueDateEpochDay = firstDue ?: (disbursementDate + customInterval),
                                contactName = contactName.trim().takeIf { it.isNotEmpty() },
                                contactPhone = contactPhone.trim().takeIf { it.isNotEmpty() },
                                notes = notes.trim().takeIf { it.isNotEmpty() },
                            ),
                        )
                    } else {
                        container.obligationRepository.saveEmi(
                            EmiPurchaseEntity(
                                id = editId ?: 0L,
                                productName = product.trim(),
                                merchant = merchant.trim(),
                                purchaseDateEpochDay = purchaseDate,
                                cashPriceMinor = cashPriceText.let { amount(it) },
                                totalPayableMinor = effectiveTotal,
                                downPaymentMinor = downPayment,
                                emiAmountMinor = installmentAmount,
                                installmentCount = count,
                                installmentFrequency = frequency.name,
                                customIntervalDays = customInterval,
                                firstDueDateEpochDay = firstDue ?: (purchaseDate + customInterval),
                                notes = notes.trim().takeIf { it.isNotEmpty() },
                            ),
                        )
                    }
                    saving = false
                    when (result) {
                        is SaveResult.Saved -> onDone()
                        is SaveResult.Invalid -> error = result.message
                        is SaveResult.Conflict -> error = result.message
                        is SaveResult.Mismatch -> error = result.message
                    }
                }
            },
        )
    }
}

